# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.outFile.down_file_pb2 as down__file__pb2


class FileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.downFile = channel.unary_unary(
                '/file.File/downFile',
                request_serializer=down__file__pb2.DownFileInfoRequest.SerializeToString,
                response_deserializer=down__file__pb2.DownFileSynchronizationResultResponse.FromString,
                )


class FileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def downFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'downFile': grpc.unary_unary_rpc_method_handler(
                    servicer.downFile,
                    request_deserializer=down__file__pb2.DownFileInfoRequest.FromString,
                    response_serializer=down__file__pb2.DownFileSynchronizationResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'file.File', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class File(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def downFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/file.File/downFile',
            down__file__pb2.DownFileInfoRequest.SerializeToString,
            down__file__pb2.DownFileSynchronizationResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
