# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: down-file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='down-file.proto',
  package='file',
  syntax='proto3',
  serialized_options=b'\n\tprotoFileB\004fileP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x64own-file.proto\x12\x04\x66ile\"\x8b\x01\n\x13\x44ownFileInfoRequest\x12\x0f\n\x07\x64ownUrl\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x36\n\toperation\x18\x03 \x01(\x0e\x32#.file.DownFileInfoRequest.Operation\"\x1a\n\tOperation\x12\r\n\tDOWN_FILE\x10\x00\"q\n%DownFileSynchronizationResultResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08\x66ilesize\x18\x03 \x01(\t\x12\x17\n\x0f\x66ileFragmentNum\x18\x04 \x01(\t2Z\n\x04\x46ile\x12R\n\x08\x64ownFile\x12\x19.file.DownFileInfoRequest\x1a+.file.DownFileSynchronizationResultResponseB\x13\n\tprotoFileB\x04\x66ileP\x01\x62\x06proto3'
)



_DOWNFILEINFOREQUEST_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='file.DownFileInfoRequest.Operation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DOWN_FILE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=139,
  serialized_end=165,
)
_sym_db.RegisterEnumDescriptor(_DOWNFILEINFOREQUEST_OPERATION)


_DOWNFILEINFOREQUEST = _descriptor.Descriptor(
  name='DownFileInfoRequest',
  full_name='file.DownFileInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='downUrl', full_name='file.DownFileInfoRequest.downUrl', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='file.DownFileInfoRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation', full_name='file.DownFileInfoRequest.operation', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DOWNFILEINFOREQUEST_OPERATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=165,
)


_DOWNFILESYNCHRONIZATIONRESULTRESPONSE = _descriptor.Descriptor(
  name='DownFileSynchronizationResultResponse',
  full_name='file.DownFileSynchronizationResultResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='file.DownFileSynchronizationResultResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='file.DownFileSynchronizationResultResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filesize', full_name='file.DownFileSynchronizationResultResponse.filesize', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fileFragmentNum', full_name='file.DownFileSynchronizationResultResponse.fileFragmentNum', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=280,
)

_DOWNFILEINFOREQUEST.fields_by_name['operation'].enum_type = _DOWNFILEINFOREQUEST_OPERATION
_DOWNFILEINFOREQUEST_OPERATION.containing_type = _DOWNFILEINFOREQUEST
DESCRIPTOR.message_types_by_name['DownFileInfoRequest'] = _DOWNFILEINFOREQUEST
DESCRIPTOR.message_types_by_name['DownFileSynchronizationResultResponse'] = _DOWNFILESYNCHRONIZATIONRESULTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DownFileInfoRequest = _reflection.GeneratedProtocolMessageType('DownFileInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOWNFILEINFOREQUEST,
  '__module__' : 'down_file_pb2'
  # @@protoc_insertion_point(class_scope:file.DownFileInfoRequest)
  })
_sym_db.RegisterMessage(DownFileInfoRequest)

DownFileSynchronizationResultResponse = _reflection.GeneratedProtocolMessageType('DownFileSynchronizationResultResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOWNFILESYNCHRONIZATIONRESULTRESPONSE,
  '__module__' : 'down_file_pb2'
  # @@protoc_insertion_point(class_scope:file.DownFileSynchronizationResultResponse)
  })
_sym_db.RegisterMessage(DownFileSynchronizationResultResponse)


DESCRIPTOR._options = None

_FILE = _descriptor.ServiceDescriptor(
  name='File',
  full_name='file.File',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=282,
  serialized_end=372,
  methods=[
  _descriptor.MethodDescriptor(
    name='downFile',
    full_name='file.File.downFile',
    index=0,
    containing_service=None,
    input_type=_DOWNFILEINFOREQUEST,
    output_type=_DOWNFILESYNCHRONIZATIONRESULTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILE)

DESCRIPTOR.services_by_name['File'] = _FILE

# @@protoc_insertion_point(module_scope)
